CREATE TABLE IF NOT EXISTS data_box_actions (
  id TEXT PRIMARY KEY,
  message_id TEXT NOT NULL,
  data_box_id TEXT,
  action_type TEXT NOT NULL CHECK (action_type IN ('archive', 'email', 'reply')),
  status TEXT NOT NULL CHECK (status IN ('prepared', 'requires_confirmation', 'confirmed', 'sent', 'archived', 'blocked', 'failed', 'skipped')),
  recipient TEXT,
  subject TEXT,
  body_preview TEXT,
  dedupe_key TEXT NOT NULL,
  requested_by_user_id TEXT,
  requested_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  confirmed_at TEXT,
  completed_at TEXT,
  provider TEXT,
  provider_message_id TEXT,
  result_json TEXT,
  error_code TEXT,
  error_message TEXT,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (message_id) REFERENCES data_box_messages(id),
  FOREIGN KEY (data_box_id) REFERENCES data_boxes(id)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_data_box_actions_dedupe
  ON data_box_actions(dedupe_key);

CREATE INDEX IF NOT EXISTS idx_data_box_actions_message
  ON data_box_actions(message_id, action_type, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_data_box_actions_status
  ON data_box_actions(status, action_type, created_at DESC);

INSERT INTO module_rules (
  id,
  module_key,
  title,
  description,
  type,
  status,
  conditions_json,
  actions_json,
  is_automation,
  trigger_type,
  schedule_cron,
  event_name,
  cloud_runner,
  last_run_at,
  next_run_at,
  last_run_status,
  last_run_message,
  created_by_user_id,
  created_at,
  updated_by_user_id,
  updated_at
) VALUES
(
  'data-box-registr-smluv-archive',
  'data-box',
  'Registr smluv archivovat',
  'Archivuje informacni zpravy Registru smluv.',
  'automation',
  'active',
  '{"anySender":["Registr smluv","Digitální a informační agentura"],"anyText":["Zveřejnění","veřejnění smlouvy"]}',
  '{"type":"ARCHIVE"}',
  1,
  'time',
  '*/30 * * * *',
  '',
  'data-box-cloud-runner',
  NULL,
  NULL,
  NULL,
  NULL,
  'system',
  CURRENT_TIMESTAMP,
  'system',
  CURRENT_TIMESTAMP
),
(
  'data-box-jmhz-send-gt-brno',
  'data-box',
  'JMHZ poslat GT Brno',
  'Pripravi e-mail pro GT Brno u odpovedi JMHZ/CSSZ.',
  'automation',
  'active',
  '{"anySender":["JMHZ","Česká správa sociálního zabezpečení"],"anyText":["Odpověď na ePodání JMH","Protokol o kompletnosti","Hlášení je částečně přijato"]}',
  '{"type":"SEND_EMAIL","recipients":["tehlarova@gtbrno.cz","trnkova@gtbrno.cz"]}',
  1,
  'time',
  '*/30 * * * *',
  '',
  'data-box-cloud-runner',
  NULL,
  NULL,
  NULL,
  NULL,
  'system',
  CURRENT_TIMESTAMP,
  'system',
  CURRENT_TIMESTAMP
),
(
  'data-box-cssz-epodani-archive',
  'data-box',
  'e-podání ČSSZ archivovat',
  'Archivuje odpovedi e-podani CSSZ.',
  'automation',
  'active',
  '{"anySender":["e-podání ČSSZ","Česká správa sociálního zabezpečení"],"anyText":["Odpověď na e-Podání z DZ"]}',
  '{"type":"ARCHIVE"}',
  1,
  'time',
  '*/30 * * * *',
  '',
  'data-box-cloud-runner',
  NULL,
  NULL,
  NULL,
  NULL,
  'system',
  CURRENT_TIMESTAMP,
  'system',
  CURRENT_TIMESTAMP
),
(
  'data-box-exekutor-jicha-send-gt-brno',
  'data-box',
  'Exekutor Jícha poslat GT Brno',
  'Pripravi e-mail pro GT Brno u exekutora Jichy.',
  'automation',
  'active',
  '{"anySender":["Jícha Lukáš","soudní exekutor"],"anyText":["203 Ex","Usnesení o zrušení EP"]}',
  '{"type":"SEND_EMAIL","recipients":["tehlarova@gtbrno.cz","trnkova@gtbrno.cz"]}',
  1,
  'time',
  '*/30 * * * *',
  '',
  'data-box-cloud-runner',
  NULL,
  NULL,
  NULL,
  NULL,
  'system',
  CURRENT_TIMESTAMP,
  'system',
  CURRENT_TIMESTAMP
),
(
  'data-box-culligan-send-faktury',
  'data-box',
  'Culligan poslat na faktury',
  'Pripravi e-mail na faktury u upominek Culligan.',
  'automation',
  'active',
  '{"anySender":["Culligan Water Czech s.r.o."],"anyText":["předžalobní upomínka","upomínka"]}',
  '{"type":"SEND_EMAIL","recipients":["faktury@kaiserservis.cz"]}',
  1,
  'time',
  '*/30 * * * *',
  '',
  'data-box-cloud-runner',
  NULL,
  NULL,
  NULL,
  NULL,
  'system',
  CURRENT_TIMESTAMP,
  'system',
  CURRENT_TIMESTAMP
),
(
  'data-box-csu-urgence-archive',
  'data-box',
  'ČSÚ urgence archivovat',
  'Archivuje urgence Ceskeho statistickeho uradu.',
  'automation',
  'active',
  '{"anySender":["Český statistický úřad"],"anyText":["Odeslání urgence","urgenční dopis","EP 5-01"]}',
  '{"type":"ARCHIVE"}',
  1,
  'time',
  '*/30 * * * *',
  '',
  'data-box-cloud-runner',
  NULL,
  NULL,
  NULL,
  NULL,
  'system',
  CURRENT_TIMESTAMP,
  'system',
  CURRENT_TIMESTAMP
),
(
  'data-box-podebrady-send-dispecer',
  'data-box',
  'Poděbrady poslat dispečerovi',
  'Pripravi e-mail dispecerovi u zprav z Podebrad.',
  'automation',
  'active',
  '{"anySender":["Technické služby města Poděbrad"],"anyText":["čipování","podnikatelských nádob"]}',
  '{"type":"SEND_EMAIL","recipients":["dispecer@kaiserservis.cz"]}',
  1,
  'time',
  '*/30 * * * *',
  '',
  'data-box-cloud-runner',
  NULL,
  NULL,
  NULL,
  NULL,
  'system',
  CURRENT_TIMESTAMP,
  'system',
  CURRENT_TIMESTAMP
)
ON CONFLICT(id) DO UPDATE SET
  title = excluded.title,
  description = excluded.description,
  type = excluded.type,
  status = excluded.status,
  conditions_json = excluded.conditions_json,
  actions_json = excluded.actions_json,
  is_automation = excluded.is_automation,
  trigger_type = excluded.trigger_type,
  schedule_cron = excluded.schedule_cron,
  cloud_runner = excluded.cloud_runner,
  updated_by_user_id = 'system',
  updated_at = CURRENT_TIMESTAMP;
